name: Release Candidate Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v3

      - name: Create Release Tag
        id: tag
        run: |
          git pull --tags
          VERSION=`/bin/bash tag.sh -m staging`
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo $VERSION